
//Pizza composition
export const COMPOSITION_INITIALIZE = 'COMPOSITION_INITIALIZE';
export const COMPOSITION_INCREMENT = 'COMPOSITION_INCREMENT';
export const COMPOSITION_DECREMENT = 'COMPOSITION_DECREMENT';


//Pizza builder state
export const BUILD_SAVED = 'BUILD_SAVED';
